### ISSUE TITLE
Add support to optional ignore TXT records starting with _acme-challenge.

### ISSUE THREAD

**Issue by resmo** [octodns/octodns#352] opened 2019-04-24 10:52 UTC
DNS acme (letsencrypt) challenges is often automated by a different mechanism than octodns and to have a way to optional ignore them (race condition) might be helpful

**Comment by shaikatz** [comment] 2019-10-03 14:21
@ross / any other maintainer, what do you think about this feature? I would like to contribute to it.

I don't think that handling specific to let's encrypt is appropriate but maybe a more general way to ignore specific records, it might be useful also for other use cases where some records have to be set independently from octodns.

**Comment by ross** [comment] 2019-10-03 14:42
Conceptually sounds reasonable. The devil would be in the implementation. I think it'd likely have to be implemented on the `Zone` object so that it would ignore it coming from all sources. That's not a concept that currently implemented and without digging into it I don't know how much that'd involve. 

The `Manager` object currently just builds up the list of sources and targets and passes that into the point at which the `Zone` object is created. Getting this going would probably require some refactoring or at least extra plumbing to get the full zone config into the populate process so that the `Zone` could be told to ignore things.

**Comment by shaikatz** [comment] 2019-10-03 15:35
I'll try to dig into that and see if I can come up with a reasonable solution.
Unfortunately, python is not my strongest language, so it might take some time.

**Comment by jasperroel** [comment] 2021-08-05 12:41
I ran into this today, when OctoDNS wants to delete a bunch of DNS records created by letsencrypt.

A note for others - this isn't technically a bad thing (those records can be cleared after you get the cert, see https://community.letsencrypt.org/t/the-dns-challenge-entry-can-be-immediately-cleared-out-right/27584), but it does make the plan a bit harder to read since a lot of those `DELETE`s are not what the user intended with their change.

So either a way to ignore certain entries, or to leave them out of the plan, would be nice.

**Comment by ross** [comment] 2021-08-05 13:52
This should now be possible with `Processors` https://github.com/octodns/octodns/tree/master/octodns/processor.

**Comment by ross** [comment] 2021-08-05 16:00
> This should now be possible with `Processors` https://github.com/octodns/octodns/tree/master/octodns/processor.

Implementation in https://github.com/octodns/octodns/pull/751

**Comment by jasperroel** [comment] 2021-08-06 13:53
Thanks @ross that looks good! Any idea on timelines on when this would be merged/available?

**Comment by ross** [comment] 2021-08-06 14:04
> Thanks @ross that looks good! Any idea on timelines on when this would be merged/available?

Ideally it'd get tested (at least plan, doesn't have to be applied) by someone with actual records :grin:. Past that it just needs a ✅

**Comment by jasperroel** [comment] 2021-08-06 14:05
I can do that early next week. Is there an easy way to get a branch up and running for testing?

**Comment by ross** [comment] 2021-08-06 14:06
You can install a specific branch with pip using:

`-e git+https://git@github.com/github/octodns.git@acme-ignoring-processor#egg=octodns`

**Comment by jasperroel** [comment] 2021-08-11 09:03
@ross I installed your branch, it did ignore existing entries, but I also noticed this:

I added a _new_ entry to my config, which was also promptly ignored:

`config.yaml`:
```
processors:
  acme:
    class: octodns.processor.acme.AcmeIgnoringProcessor

zones:
  example.org.:
    sources:
      - config
    targets:
      - cloudflare
    processors:
      - acme

```

`domain.yaml`:
```
_acme-challenge.added-as-an-example:
  type: TXT
  value: some-value
```

`octodns-sync --config-file config.yaml`

```
2021-08-11T10:56:26  [140471877969728] INFO  YamlProvider[config] populate:   found 33 records, exists=False
2021-08-11T10:56:26  [140471877969728] INFO  AcmeIgnoringProcessor _process: ignoring _acme-challenge.added-as-an-example.example.org.
2021-08-11T10:56:26  [140471877969728] INFO  CloudflareProvider[cloudflare] plan: desired=example.org.
2021-08-11T10:56:28  [140471877969728] INFO  CloudflareProvider[cloudflare] populate:   found 35 records, exists=True
2021-08-11T10:56:28  [140471877969728] INFO  AcmeIgnoringProcessor _process: ignoring _acme-challenge.static-dev.example.org.
2021-08-11T10:56:28  [140471877969728] INFO  AcmeIgnoringProcessor _process: ignoring _acme-challenge.app.example.org.
2021-08-11T10:56:28  [140471877969728] INFO  AcmeIgnoringProcessor _process: ignoring _acme-challenge.app-dev.example.org.
2021-08-11T10:56:28  [140471877969728] INFO  CloudflareProvider[cloudflare] plan:   filtered out 6 changes
2021-08-11T10:56:28  [140471877969728] INFO  CloudflareProvider[cloudflare] plan:   No changes
2021-08-11T10:56:28  [140471877969728] INFO  Manager 
********************************************************************************
No changes were planned
********************************************************************************
```

Not sure if this complicates matters, or if we can just have a processor that ignore entries that are not defined in the YAML config (or just plainly does not _delete_ records, but still adds/modifies as needed by the config.

In my case, it's a mix of use-cases:
- I use **Firebase**, which requires you to have a set of `_acme-challenge` records, which I manage via the YAML config file (add and remove as needed).
- I also use **Traefik**, which uses DNS challenges to create certs on the fly, but sometimes leaves behind some unneeded `_acme-challenge` records (what this issue what initially about).

**Comment by jasperroel** [comment] 2021-08-11 13:56
Yes, agreed. And I think the solution as offered is a nice one (especially, as a processor, it's useful to folks with similar Letsencrypt setups).

I understand my personal setup is probably not a common one, we can probably ignore it and merge this in, as the functionality as intended is working :+1:.

**Comment by ross** [comment] 2021-08-11 14:25
So just filed https://github.com/octodns/octodns/pull/753 which is an add on to https://github.com/octodns/octodns/pull/751. It works by adding an extra value to the acme TXT records to mark it as managed by octoDNS. Not 100% sure it'll work, depends on whether the acme verifier stuff is OK with other values existing in the records. Based on reading https://letsencrypt.org/docs/challenge-types/#dns-01-challenge it does talk about having multiple values when verifying multiple cert types so I'm guessing it will be fine with it. 

@jasperroel I don't have any DNS challenge stuff set up at the moment so if you want to check and see if the verification works with other values in the TXT in addition to the secret bit we can move forward with the add on. It seems like a reasonable solution, but I don't want to write tests for that route unless it'll work so...

**Comment by jasperroel** [comment] 2021-08-11 14:36
I just tried your branch and get this as a plan now (without changes to my config):

# as-is
```
********************************************************************************
* example.org.
********************************************************************************
* cloudflare (CloudflareProvider)
*   Create <TxtRecord TXT 43200, _acme-challenge.app.example.org., ['*octoDNS*', 'JEKC4j6NBSlTkHL6wLgDFKwjEFnj51OmWezVLN_1rNc']> (config)
*   Create <TxtRecord TXT 43200, _acme-challenge.app-dev.example.org., ['*octoDNS*', 'NGkhtFiTjTV_OihBOP6O-lDMEHd1hbkQGfSCAVMXgKk']> (config)
*   Create <TxtRecord TXT 43200, _acme-challenge.static-dev.example.org., ['*octoDNS*', 'u0AHhv0nozQr3sxabZlOiPExBnMZwSEvG07JBOKYHDU']> (config)
*   Summary: Creates=3, Updates=0, Deletes=0, Existing Records=32
********************************************************************************
```
which is good :-).

# new ACME entry
I added this to `example.org.yaml`:
```
_acme-challenge.new-value:
  type: TXT
  value: just added this
```

Which creates this plan:
```
********************************************************************************
* example.org.
********************************************************************************
* cloudflare (CloudflareProvider)
*   Create <TxtRecord TXT 43200, _acme-challenge.app.example.org., ['*octoDNS*', 'JEKC4j6NBSlTkHL6wLgDFKwjEFnj51OmWezVLN_1rNc']> (config)
*   Create <TxtRecord TXT 43200, _acme-challenge.app-dev.example.org., ['*octoDNS*', 'NGkhtFiTjTV_OihBOP6O-lDMEHd1hbkQGfSCAVMXgKk']> (config)
*   Create <TxtRecord TXT 43200, _acme-challenge.new-value.example.org., ['*octoDNS*', 'just added this']> (config)
*   Create <TxtRecord TXT 43200, _acme-challenge.static-dev.example.org., ['*octoDNS*', 'u0AHhv0nozQr3sxabZlOiPExBnMZwSEvG07JBOKYHDU']> (config)
*   Summary: Creates=4, Updates=0, Deletes=0, Existing Records=32
********************************************************************************
```

I think that is _missing_ the actual creation of the `new-value` `TXT` record?

I would expect a 5th create:
`*   Create <TxtRecord TXT 43200, _acme-challenge.new-value.example.org., ['just added this']> (config)`
(so, without the `'*octoDNS*'`)?

**Comment by jasperroel** [comment] 2021-08-11 14:39
Ah, also this creates trouble with trying to actually apply it with `--doit`:
```
2021-08-11T16:37:40  [139710655522624] DEBUG CloudflareProvider[cloudflare] _request: method=POST, path=/zones/.../dns_records
2021-08-11T16:37:41  [139710655522624] DEBUG urllib3.connectionpool https://api.cloudflare.com:443 "POST /client/v4/zones/.../dns_records HTTP/1.1" 400 None
2021-08-11T16:37:41  [139710655522624] DEBUG CloudflareProvider[cloudflare] _request:   status=400
2021-08-11T16:37:41  [139710655522624] DEBUG CloudflareProvider[cloudflare] _request:   data={'content': 'NGkhtFiTjTV_OihBOP6O-lDMEHd1hbkQGfSCAVMXgKk', 'name': '_acme-challenge.app-dev.example.org', 'type': 'TXT', 'ttl': 43200}
Traceback (most recent call last):
  File "/home/jasperroel/git/home/dns/venv/bin/octodns-sync", line 33, in <module>
    sys.exit(load_entry_point('octodns', 'console_scripts', 'octodns-sync')())
  File "/home/jasperroel/git/home/dns/venv/src/octodns/octodns/cmds/sync.py", line 38, in main
    manager.sync(eligible_zones=args.zone, eligible_sources=args.source,
  File "/home/jasperroel/git/home/dns/venv/src/octodns/octodns/manager.py", line 474, in sync
    total_changes += target.apply(plan)
  File "/home/jasperroel/git/home/dns/venv/src/octodns/octodns/provider/base.py", line 101, in apply
    self._apply(plan)
  File "/home/jasperroel/git/home/dns/venv/src/octodns/octodns/provider/cloudflare.py", line 823, in _apply
    getattr(self, '_apply_{}'.format(class_name))(change)
  File "/home/jasperroel/git/home/dns/venv/src/octodns/octodns/provider/cloudflare.py", line 640, in _apply_Create
    self._try_request('POST', path, data=content)
  File "/home/jasperroel/git/home/dns/venv/src/octodns/octodns/provider/cloudflare.py", line 119, in _try_request
    return self._request(*args, **kwargs)
  File "/home/jasperroel/git/home/dns/venv/src/octodns/octodns/provider/cloudflare.py", line 138, in _request
    raise CloudflareError(resp.json())
octodns.provider.cloudflare.CloudflareError: Record already exists.
```

**Comment by jasperroel** [comment] 2021-08-11 14:42
After applying `--doit` a few times, it eventually ends up with all the work done:

![image](https://user-images.githubusercontent.com/1370303/129049989-07ebf7e3-fb58-4f51-add2-99cad5a5564a.png)

```
2021-08-11T16:42:07  [140538155775808] INFO  Manager __init__:   max_workers=1
2021-08-11T16:42:07  [140538155775808] INFO  Manager __init__:   include_meta=False
2021-08-11T16:42:07  [140538155775808] INFO  Manager sync: eligible_zones=[], eligible_targets=[], dry_run=True, force=False, plan_output_fh=<stdout>
2021-08-11T16:42:07  [140538155775808] INFO  Manager sync:   zone=example.org.
2021-08-11T16:42:07  [140538155775808] INFO  Manager sync:   sources=['config'] -> targets=['cloudflare']
2021-08-11T16:42:07  [140538155775808] INFO  YamlProvider[config] populate:   found 36 records, exists=False
2021-08-11T16:42:07  [140538155775808] INFO  CloudflareProvider[cloudflare] plan: desired=example.org.
2021-08-11T16:42:10  [140538155775808] INFO  CloudflareProvider[cloudflare] populate:   found 36 records, exists=True
2021-08-11T16:42:10  [140538155775808] INFO  CloudflareProvider[cloudflare] plan:   filtered out 6 changes
2021-08-11T16:42:10  [140538155775808] INFO  CloudflareProvider[cloudflare] plan:   No changes
2021-08-11T16:42:10  [140538155775808] INFO  Manager 
********************************************************************************
No changes were planned
********************************************************************************
```

**Comment by jasperroel** [comment] 2021-08-11 14:45
To be safe, I also added a bogus entry from letsencrypt:
![image](https://user-images.githubusercontent.com/1370303/129050557-ffa88065-d4b7-44cf-8569-49c3a676563e.png)

And ran the sync/plan:
```
2021-08-11T16:43:41  [140263218710336] INFO  YamlProvider[config] populate:   found 36 records, exists=False
2021-08-11T16:43:41  [140263218710336] INFO  CloudflareProvider[cloudflare] plan: desired=example.org.
2021-08-11T16:43:44  [140263218710336] INFO  CloudflareProvider[cloudflare] populate:   found 37 records, exists=True
2021-08-11T16:43:44  [140263218710336] INFO  AcmeIgnoringProcessor _process: ignoring _acme-challenge.added-dynamically.example.org.
2021-08-11T16:43:44  [140263218710336] INFO  CloudflareProvider[cloudflare] plan:   filtered out 6 changes
2021-08-11T16:43:44  [140263218710336] INFO  CloudflareProvider[cloudflare] plan:   No changes
2021-08-11T16:43:44  [140263218710336] INFO  Manager 
********************************************************************************
No changes were planned
********************************************************************************
```

So your solution is definitely working (after applying it a few times)

**Comment by ross** [comment] 2021-08-11 14:53
> ```
> *   Create <TxtRecord TXT 43200, _acme-challenge.new-value.example.org., ['*octoDNS*', 'just added this']> (config)
> ```
> 
> I think that is _missing_ the actual creation of the `new-value` `TXT` record?

It's there. 

> I would expect a 5th create:
> `* Create <TxtRecord TXT 43200, _acme-challenge.new-value.example.org., ['just added this']> (config)`
> (so, without the `'*octoDNS*'`)?

All of the octoDNS managed ones will have the 2nd value added to mark it as something octoDNS owns.



> Ah, also this creates trouble with trying to actually apply it with `--doit`:

> ```
> octodns.provider.cloudflare.CloudflareError: Record already exists.
> ```

The PR assumes that anything in the config doesn't exist in the provider yet and it will add it and the ownership value at the same time. I suspect some of the values in the config already existed in Cloudflare and the PR doesn't handle that situation since it doesn't know that it owns them. It might be possible to take over records like that, but it will require more code than currently exists. I think the processor would have to record things it saw in the source so that when it sees them unowned in the target it could let them through and take over and manage them rather than try and replace them. Will look into this, but probably won't be until alter today as I'm afk starting soon.

**Comment by jasperroel** [comment] 2021-08-11 14:55
Yeah, totally understand. If the "existing records need to be adopted since that's not currently handled" is acceptable (it is to me, since it's a one-time operation and will work once that's done), then the proposed solution (#753) is :+1:

**Comment by jasperroel** [comment] 2021-08-11 14:57
Also, just testing this - deleting them from the config also deletes both TXT records from DNS, which is a nice bonus:
```
********************************************************************************
* example.org.
********************************************************************************
* cloudflare (CloudflareProvider)
*   Delete <TxtRecord TXT 43200, _acme-challenge.new-value.example.org., ['*octoDNS*', 'just added this']>
*   Delete <TxtRecord TXT 43200, _acme-challenge.new-value-after-having-owned-the-rest.example.org., ['*octoDNS*', 'just added this after having *octodns* applied to the rest']>
*   Summary: Creates=0, Updates=0, Deletes=2, Existing Records=37
********************************************************************************


2021-08-11T16:56:11  [140435961808704] INFO  CloudflareProvider[cloudflare] apply: making 2 changes to example.org.
2021-08-11T16:56:15  [140435961808704] INFO  Manager sync:   2 total changes
```

**Comment by ross** [comment] 2021-08-11 16:33
Ok. Pushed up a change that should allow octoDNS to take ownership of existing acme records that are later put into the config.

**Comment by ross** [comment] 2021-08-11 17:52
Secondary branch has been merged in. The ownership stuff should now be functional and has tests/coverage.

**Comment by jasperroel** [comment] 2021-08-12 06:32
:+1: 

The adoption works as well in one go now as well. Thank you for spending the time on this feature!

<summary>Plan output</summary>
<details>

```
********************************************************************************
* example.org.
********************************************************************************
* cloudflare (CloudflareProvider)
*   Update
*     <TxtRecord TXT 43200, _acme-challenge.app.example.org., ['JEKC4j6NBSlTkHL6wLgDFKwjEFnj51OmWezVLN_1rNc']> ->
*     <TxtRecord TXT 43200, _acme-challenge.app.example.org., ['*octoDNS*', 'JEKC4j6NBSlTkHL6wLgDFKwjEFnj51OmWezVLN_1rNc']> (config)
*   Update
*     <TxtRecord TXT 43200, _acme-challenge.app-dev.example.org., ['NGkhtFiTjTV_OihBOP6O-lDMEHd1hbkQGfSCAVMXgKk']> ->
*     <TxtRecord TXT 43200, _acme-challenge.app-dev.example.org., ['*octoDNS*', 'NGkhtFiTjTV_OihBOP6O-lDMEHd1hbkQGfSCAVMXgKk']> (config)
*   Update
*     <TxtRecord TXT 43200, _acme-challenge.static-dev.example.org., ['u0AHhv0nozQr3sxabZlOiPExBnMZwSEvG07JBOKYHDU']> ->
*     <TxtRecord TXT 43200, _acme-challenge.static-dev.example.org., ['*octoDNS*', 'u0AHhv0nozQr3sxabZlOiPExBnMZwSEvG07JBOKYHDU']> (config)
*   Summary: Creates=0, Updates=3, Deletes=0, Existing Records=35
********************************************************************************


2021-08-12T08:30:36  [140340366546752] INFO  CloudflareProvider[cloudflare] apply: making 3 changes to example.org.
2021-08-12T08:30:43  [140340366546752] INFO  Manager sync:   3 total changes
```

</details>

**Closed** 2021-08-14 15:05 UTC
