### ISSUE TITLE
Lots of updates every time even after successful synchronisation [route53 -> bind9]

### ISSUE THREAD

**Issue by paxlo** [octodns/octodns#1146] opened 2024-03-05 13:21 UTC
I am using octodns/octodns:2024.02 in cron to periodically synchronise (every 5 minutes) a zone from source route53 to target rfc2136 (bind9). Target successfully receives the changes and resolves them, but on each new sync, octodns detects tons of updated CNAME and SRV records, even though the records have not been updated

```
# octodns-sync --config-file /opt/octodns/config.yaml --doit --force

2024-03-05T12:44:09  [140531509234560] INFO  Manager _config_include_meta: include_meta=False
2024-03-05T12:44:09  [140531509234560] INFO  Manager _config_enable_checksum: enable_checksum=False
2024-03-05T12:44:09  [140531509234560] INFO  Manager _config_auto_arpa: auto_arpa=False
2024-03-05T12:44:09  [140531509234560] INFO  Manager __init__: global_processors=[]
2024-03-05T12:44:09  [140531509234560] INFO  Manager __init__: global_post_processors=[]
2024-03-05T12:44:09  [140531509234560] INFO  Route53Provider[route53] __init__: id=route53, access_key_id=ACCESS_KEY_ID, max_changes=1000, delegation_set_id=None, get_zones_by_name=False
2024-03-05T12:44:09  [140531509234560] INFO  Manager __init__: provider=route53 (octodns_route53 0.0.6)
2024-03-05T12:44:09  [140531509234560] INFO  Manager __init__: provider=rfc2136 (octodns_bind 0.0.6)
2024-03-05T12:44:09  [140531509234560] INFO  Manager __init__: processor=no-root-ns (octodns.processor.filter 1.5.0)
2024-03-05T12:44:09  [140531509234560] INFO  Manager __init__: processor=exclude-root-ns-changes (octodns.processor.filter 1.5.0)
2024-03-05T12:44:09  [140531509234560] INFO  Manager __init__: processor=only-these-types (octodns.processor.filter 1.5.0)
2024-03-05T12:44:09  [140531509234560] INFO  Manager __init__: processor=not-these-names (octodns.processor.filter 1.5.0)
2024-03-05T12:44:09  [140531509234560] INFO  Manager sync: eligible_zones=[], eligible_targets=[], dry_run=False, force=True, plan_output_fh=<stdout>, checksum=None
2024-03-05T12:44:09  [140531509234560] INFO  Manager sync:   zone=exampleddd.internal.
2024-03-05T12:44:09  [140531509234560] INFO  Manager sync:     sources=['route53']
2024-03-05T12:44:09  [140531509234560] INFO  Manager sync:     processors=['no-root-ns', 'exclude-root-ns-changes', 'only-these-types', 'not-these-names']
2024-03-05T12:44:09  [140531509234560] INFO  Manager sync:     targets=['rfc2136']
2024-03-05T12:44:10  [140531509234560] WARNING Record Invalid record "api.exampleddd.internal."
  - CNAME value "karazhan.eks.aws.exampleddd.internal" missing trailing .
2024-03-05T12:44:10  [140531509234560] WARNING Record Invalid record "argocd.exampleddd.internal."
  - CNAME value "naxxramas.eks.aws.exampleddd.internal" missing trailing .
2024-03-05T12:44:10  [140531509234560] WARNING Record Invalid record "auth.exampleddd.internal."
...
...
...
...
...
...
2024-03-05T13:04:26  [139794038217600] INFO  Route53Provider[route53] populate:   found 871 records, exists=True
2024-03-05T13:04:26  [139794038217600] INFO  Rfc2136Provider[rfc2136] plan: desired=exampleddd.internal.
2024-03-05T13:04:26  [139794038217600] INFO  Rfc2136Provider[rfc2136] populate:   found 450 records
2024-03-05T13:04:26  [139794038217600] WARNING Rfc2136Provider[rfc2136] root NS record supported, but no record is configured for exampleddd.internal.
2024-03-05T13:04:26  [139794038217600] INFO  Rfc2136Provider[rfc2136] root NS record in existing, but not supported or not configured; ignoring it
2024-03-05T13:04:26  [139794038217600] INFO  Rfc2136Provider[rfc2136] plan:   Creates=0, Updates=287, Deletes=0, Existing Records=447
287
2024-03-05T13:04:26  [139794038217600] INFO  Plan 
********************************************************************************
* exampleddd.internal.
********************************************************************************
* rfc2136 (Rfc2136Provider)
*   Update
*     <SrvRecord SRV 300, _control-plane._tcp.midgard.k8s.rax.exampleddd.internal., [''1 1 6443 control-plane-1.midgard.k8s.rax.exampleddd.internal.exampleddd.internal.'', ''1 1 6443 control-plane-2.midgard.k8s.rax.exampleddd.internal.exampleddd.internal.'', ''1 1 6443 c
ontrol-plane-3.midgard.k8s.rax.exampleddd.internal.exampleddd.internal.'']> ->
*     <SrvRecord SRV 300, _control-plane._tcp.midgard.k8s.rax.exampleddd.internal., [''1 1 6443 control-plane-1.midgard.k8s.rax.exampleddd.internal'', ''1 1 6443 control-plane-2.midgard.k8s.rax.exampleddd.internal'', ''1 1 6443 control-plane-3.midgard.k8s.rax.exampleddd.
internal'']> (route53)
*   Update
*     <SrvRecord SRV 300, _control-plane._tcp.nordrassil.k8s.sandbox.exampleddd.internal., [''1 1 6443 control-plane-1.nordrassil.k8s.sandbox.exampleddd.internal.exampleddd.internal.'', ''1 1 6443 control-plane-2.nordrassil.k8s.sandbox.exampleddd.internal.exampleddd.inte
rnal.'', ''1 1 6443 control-plane-3.nordrassil.k8s.sandbox.exampleddd.internal.exampleddd.internal.'']> ->
*     <SrvRecord SRV 300, _control-plane._tcp.nordrassil.k8s.sandbox.exampleddd.internal., [''1 1 6443 control-plane-1.nordrassil.k8s.sandbox.exampleddd.internal'', ''1 1 6443 control-plane-2.nordrassil.k8s.sandbox.exampleddd.internal'', ''1 1 6443 control-plane-3.nordra
ssil.k8s.sandbox.exampleddd.internal'']> (route53)
...
...
...
...
...
...
*   Update
*     <CnameRecord CNAME 300, vector.dev.exampleddd.internal., balancer-1.dev.exampleddd.internal.exampleddd.internal.> ->
*     <CnameRecord CNAME 300, vector.dev.exampleddd.internal., balancer-1.dev.exampleddd.internal> (route53)
*   Update
*     <CnameRecord CNAME 1000, verbalist.kb.dev.exampleddd.internal., midgard.k8s.rax.exampleddd.internal.exampleddd.internal.> ->
*     <CnameRecord CNAME 1000, verbalist.kb.dev.exampleddd.internal., midgard.k8s.rax.exampleddd.internal> (route53)
*   Update
*     <CnameRecord CNAME 1000, verbalist.kb.rnd.exampleddd.internal., midgard.k8s.rax.exampleddd.internal.exampleddd.internal.> ->
*     <CnameRecord CNAME 1000, verbalist.kb.rnd.exampleddd.internal., midgard.k8s.rax.exampleddd.internal> (route53)
*   Summary: Creates=0, Updates=289, Deletes=0, Existing Records=449
********************************************************************************

2024-03-05T12:38:56  [139817847950208] INFO  Rfc2136Provider[rfc2136] apply: making 289 changes to exampleddd.internal.
2024-03-05T12:38:57  [139817847950208] INFO  Manager sync:   289 total changes

```
bind9 config:

```
key rndc-key {
    algorithm hmac-md5;
    secret "BIND_SECRET";
};

zone "exampleddd.internal." {
    type master;
    file "/var/cache/bind/exampleddd.internal";
    allow-transfer { key rndc-key; };
    allow-update { key rndc-key; };
    allow-query { any; };
    notify explicit;
};

options {
    directory "/var/cache/bind";
    allow-query       { any; };
    allow-recursion   { none; };
    allow-transfer    { none; };
    allow-update      { none; };
    auth-nxdomain     no;
    dnssec-validation no;
    listen-on         { any; };
    listen-on-v6      { none; };
    recursion         no;
    version           none;
};
```
zone file:

```
$ORIGIN exampleddd.internal.
$TTL 900
@	IN	SOA	ns-5.exampleddd.internal. hostmaster.exampleddd.internal. (
			3
			604800
			86400
			2419200
			604800
			)
$TTL 86400
    IN	NS	ns-5.exampleddd.internal.
$TTL 3600
ns-5	IN	A	10.109.0.4
```

I want to synchronise only A, CNAME, SRV records and using TypeAllowlistFilter. I also ignore  NS records changes using IgnoreRootNsFilter, ExcludeRootNsChanges, NameRejectlistFilter because NS records on target and source are different.
In addition, "lenient: True" is used here due to the fact that octodns does not find the [trailing dot](https://github.com/octodns/octodns/issues/647).

octodns config:

````
providers:
  route53:
    class: octodns_route53.Route53Provider
    access_key_id: ACCESS_KEY_ID
    secret_access_key: SECRET_ACCESS_KEY
  rfc2136:
    class: octodns_bind.Rfc2136Provider
    host: 10.109.0.4
    ipv6: False
    key_name: 'rndc-key'
    key_algorithm: 'HMAC-MD5.SIG-ALG.REG.INT'
    key_secret: BIND_SECRET
processors:
  no-root-ns:
    class: octodns.processor.filter.IgnoreRootNsFilter
  exclude-root-ns-changes:
    class: octodns.processor.filter.ExcludeRootNsChanges
    error: false
  only-these-types:
    class: octodns.processor.filter.TypeAllowlistFilter
    allowlist:
      - A
      - CNAME
      - SRV
  not-these-names:
    class: octodns.processor.filter.NameRejectlistFilter
    rejectlist:
        - ns-5
zones:
  exampleddd.internal.:
    lenient: True
    sources:
      - route53
    processors:
      - no-root-ns
      - exclude-root-ns-changes
      - only-these-types
      - not-these-names
    targets:
      - rfc2136
````

**Comment by ross** [comment] 2024-03-05 15:49
Haven't looked into the code yet, but looking at the changes (formatted to be a little easier to discern) it looks like the bind9 side of things is double appending the domain name:

```
<SrvRecord SRV 300, _control-plane._tcp.midgard.k8s.rax.exampleddd.internal., [
    ''1 1 6443 control-plane-1.midgard.k8s.rax.exampleddd.internal.exampleddd.internal.'',
    ''1 1 6443 control-plane-2.midgard.k8s.rax.exampleddd.internal.exampleddd.internal.'',
    ''1 1 6443 control-plane-3.midgard.k8s.rax.exampleddd.internal.exampleddd.internal.'']> ->
<SrvRecord SRV 300, _control-plane._tcp.midgard.k8s.rax.exampleddd.internal., [
    ''1 1 6443 control-plane-1.midgard.k8s.rax.exampleddd.internal'',
    ''1 1 6443 control-plane-2.midgard.k8s.rax.exampleddd.internal'',
    ''1 1 6443 control-plane-3.midgard.k8s.rax.exampleddd.internal'']> (route53)
```

My guess would be something is happening inside of bind9 that's assuming the SRV records are relative and then appending the domain.

**Comment by ross** [comment] 2024-03-05 17:00
I just duplicated your record data afaict the extra ending doesn't seem to come from bind:

```
_srv.tcp:
  type: SRV
  values:
    - port: 6443
      priority: 1
      target: control-plane-1.midgard.k8s.rax.exxampled.com.
      weight: 1
    - port: 6443
      priority: 1
      target: control-plane-2.midgard.k8s.rax.exxampled.com.
      weight: 1
    - port: 6443
      priority: 1
      target: control-plane-3.midgard.k8s.rax.exxampled.com.
      weight: 1
```

First `--doit` created the record, subsequent plans don't see any changes.

I tried using both Route53 and ns1 as the source and bind9 as the target.

**Comment by ross** [comment] 2024-03-05 17:05
I noticed that you have `lenient: True` set so as a second pass at things. I removed the trailing `.` from the end of the `target`s and pushed that to Route53. That DOES reproduce what you're seeing:

```console
********************************************************************************
* exxampled.com.
********************************************************************************
* rfc2136 (Rfc2136Provider)
*   Update
*     <SrvRecord SRV 86400, _srv.tcp.exxampled.com., [''1 1 6443 control-plane-1.midgard.k8s.rax.exxampled.com.exxampled.com.'', ''1 1 6443 control-plane-2.midgard.k8s.rax.exxampled.com.exxampled.com.'', ''1 1 6443 control-plane-3.midgard.k8s.rax.exxampled.com.exxampled.com.'']> ->
*     <SrvRecord SRV 86400, _srv.tcp.exxampled.com., [''1 1 6443 control-plane-1.midgard.k8s.rax.exxampled.com.'', ''1 1 6443 control-plane-2.midgard.k8s.rax.exxampled.com.'', ''1 1 6443 control-plane-3.midgard.k8s.rax.exxampled.com.'']> (route53)
*   Summary: Creates=0, Updates=1, Deletes=0, Existing Records=5
********************************************************************************
```

So it's likely you're missing trailing dots on the end of the records in Route53 and it's auto appending the domain name since they're "realtive". 

This is a good example of why the trailing dots are required in octoDNS, things behave unexpectedly w/o them. Once `lenient=True` is turned on you're kind of on your own and are signing up for dealing with these sorts of complications.

I'd wager that if you query the Route53 servers/SRV record you'd get the double zone name, but 🤷 

You're best bet is to fix those records in Route53 and append the `.` anywhere they're missing. In general try really hard to avoid `lenient=True` and as the docs say prefer using it on individual records before turning it on at the zone level if at all possible.

**Comment by igor-nikiforov** [comment] 2024-03-07 04:06
Hi @ross, we have exact same issue with same integration Route53 -> BIND9 (RFC2136).

I certainly understand problem with trailing dot but unfortunately Route53 officially declares this optional - https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/ResourceRecordTypes.html

Moreover, in our exact case it is just impossible to do it since 99% of thousands of DNS records in Route53 automatically populates from Kubernetes Ingress where specification does not accept trailing dot:
```
Failed to save resource: Ingress.extensions "my-ingress" is invalid: [spec.rules[0].host: Invalid value: "myapp.corp.internal.": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

Maybe is it possible to have some kind of option on Route53 which cover this case to avoid such issue?

Thanks!

**Comment by ross** [comment] 2024-03-07 04:54
In cases where original records can't be fixed the best/correct path would be to create a simple processor that ran through the records and added the missing `.`s where needed.

In the case that Route53 is only being used as a `source` then it could likely just implement `process_source_zone`

https://github.com/octodns/octodns/blob/3acfd174b61ff5352294a0fbb5f9fb706d76bf14/octodns/processor/base.py#L15-L32

**Comment by ross** [comment] 2024-03-07 15:01
So digging into this a bit further/explianing a bit more, this is a result of pushing a FQDN to bind9 w/o a `.` on it. bind9 is spec compliant and considers the lack of a trailing to to mean that the target is relative and it then appends the zone name w/a trailing dot, thus making the relative target a absolute one. 

```
********************************************************************************
* exxampled.com.
********************************************************************************
* rfc2136 (Rfc2136Provider)
*   Update
*     <SrvRecord SRV 86400, _srv.tcp.exxampled.com., [''1 1 6443 control-plane-1.midgard.k8s.rax.exxampled.com.exxampled.com.'', ''1 1 6443 control-plane-2.midgard.k8s.rax.exxampled.com.exxampled.com.'', ''1 1 6443 control-plane-3.midgard.k8s.rax.exxampled.com.exxampled.com.'']> ->
*     <SrvRecord SRV 86400, _srv.tcp.exxampled.com., [''1 1 6443 control-plane-1.midgard.k8s.rax.exxampled.com'', ''1 1 6443 control-plane-2.midgard.k8s.rax.exxampled.com'', ''1 1 6443 control-plane-3.midgard.k8s.rax.exxampled.com'']> (route53)
*   Summary: Creates=0, Updates=1, Deletes=0, Existing Records=5
********************************************************************************
```

This again this is specifically the sort of reason why octoDNS enforces the trailing dot b/c things get messy when providers act different w/o one. Enabling lenient is the way octoDNS lets you tell it that "I know this isn't ideal and I'm taking on whatever complications arise out of it." Best practices are best practices for a reason. 

So the fix here is NOT in octodns-route, it's doing exactly what it's supposed to. If you were to source records from any other provider (e.g. YamlProvider) w/o trailing `.` and push them into bind9 the exact same thing would happen. 

By the same token there's no fix to be made in octodns-bind. It's faithfully passing along the data that bind9 contains. 

The hiccup is that RFCs consider a missing dot to mean a relative target and the right path is to use a processor to correct the errant records. Something like the following should do the trick, it works for `CNAME`s and `SRV`s, if there are other records with "targets" missing `.`, e.g. `MX`s, then it would need to be extended to include them.

```python
from octodns.processor.base import BaseProcessor


class AddTrailingDots(BaseProcessor):
    def process_source_zone(self, desired, sources):
        for record in desired.records:
            _type = record._type
            if _type == 'CNAME' and record.value[-1] != '.':
                new = record.copy()
                new.value = f'{new.value}.'
                desired.add_record(new, replace=True)
            elif _type == 'SRV' and any(
                v.target[-1] != '.' for v in record.values
            ):
                new = record.copy()
                for value in new.values:
                    if value.target[-1] != '.':
                        value.target = f'{value.target}.'
                desired.add_record(new, replace=True)

        return desired
```

```yaml
...
processors:
  trailing-dots:
    class: trailing_dots.AddTrailingDots
...
zones:
  exxampled.com.:
    lenient: true
    sources:
      # this assumes things are pulling from Route53 as seems to be the case in this issue, but it would apply to any source 
      - route53
    processors:
      - trailing-dots
    targets:
      - bind
```

**Comment by ross** [comment] 2024-03-07 15:06
I may look into including a dot adder processor in `octodns.processors`, still thinking about whether that'd make sense or not.

**Comment by ross** [comment] 2024-03-07 20:53
> I may look into including a dot adder processor in `octodns.processors`, still thinking about whether that'd make sense or not.

/cc https://github.com/octodns/octodns/pull/1147

**Comment by igor-nikiforov** [comment] 2024-03-08 05:14
@ross thank you for addressing this!

**Comment by ross** [comment] 2024-03-11 21:56
Going to call this fixed by https://github.com/octodns/octodns/pull/1147. Will likely cut a release with the change 🔜

**Closed by ross** 2024-03-11 21:56 UTC
