### ISSUE TITLE
octodns.zone.SubzoneRecordException Error

### ISSUE THREAD

**Issue by brianeclow** [octodns/octodns#916] opened 2022-08-10 21:44 UTC
The `0.9.18` version causes an `octodns.zone.SubzoneRecordException` error. I reverted back to `0.9.17` confirm this was something new. Were there some required changes we need to implement on our local files?

On one of our bigger zones, source octodns.provider.yaml (via split), targets NS1 and Route53:

```bash
Traceback (most recent call last):
  File "/dns/env/bin/octodns-sync", line 8, in <module>
    sys.exit(main())
  File "/dns/env/lib/python3.9/site-packages/octodns/cmds/sync.py", line 64, in main
    manager.sync(
  File "/dns/env/lib/python3.9/site-packages/octodns/manager.py", line 551, in sync
    ps, d = future.result()
  File "/dns/env/lib/python3.9/site-packages/octodns/manager.py", line 77, in result
    return self.func(*self.args, **self.kwargs)
  File "/dns/env/lib/python3.9/site-packages/octodns/manager.py", line 359, in _populate_and_plan
    source.populate(zone, lenient=lenient)
  File "/dns/env/lib/python3.9/site-packages/octodns/provider/yaml.py", line 329, in populate
    self._populate_from_file(yaml_filename, zone, lenient)
  File "/dns/env/lib/python3.9/site-packages/octodns/provider/yaml.py", line 187, in _populate_from_file
    zone.add_record(
  File "/dns/env/lib/python3.9/site-packages/octodns/zone.py", line 79, in add_record
    raise SubzoneRecordException(
octodns.zone.SubzoneRecordException: Record jigglypuff.example.com. is under a managed subzone
```

On one of our parked/minimal zones, source octodns.provider.yaml, target NS1:

```bash
Traceback (most recent call last):
  File "/dns/env/bin/octodns-sync", line 8, in <module>
    sys.exit(main())
  File "/dns/env/lib/python3.9/site-packages/octodns/cmds/sync.py", line 64, in main
    manager.sync(
  File "/dns/env/lib/python3.9/site-packages/octodns/manager.py", line 551, in sync
    ps, d = future.result()
  File "/dns/env/lib/python3.9/site-packages/octodns/manager.py", line 77, in result
    return self.func(*self.args, **self.kwargs)
  File "/dns/env/lib/python3.9/site-packages/octodns/manager.py", line 359, in _populate_and_plan
    source.populate(zone, lenient=lenient)
  File "/dns/env/lib/python3.9/site-packages/octodns/provider/yaml.py", line 211, in populate
    self._populate_from_file(filename, zone, lenient)
  File "/dns/env/lib/python3.9/site-packages/octodns/provider/yaml.py", line 187, in _populate_from_file
    zone.add_record(
  File "/dns/env/lib/python3.9/site-packages/octodns/zone.py", line 84, in add_record
    raise SubzoneRecordException(
octodns.zone.SubzoneRecordException: Record example2.com. a managed sub-zone and not of type NS
```

**Comment by ross** [comment] 2022-08-10 22:46
The diff between versions is pretty huge, but 95% of it is `black` formatting. I'm guessing the problem came about as of https://github.com/octodns/octodns/pull/908 (/cc @nakato) which messes with the subzone stuff. 

@brianeclow do you have config for a couple of problematic zones handy? Looks like it's some sort of problem with `example(2)`. I'm probably not going to get a chance to dig into it today, but should be able to tomorrow morning. Once it's figured out I can cut a new release and hide 0.9.18.

**Comment by brianeclow** [comment] 2022-08-10 23:08
It is randomly throwing errors on various zones. A SplitYAML zones are like `example.com`, and all the YAML zones are like `example2.com` off the following template:

```yaml
---
? ''
: - type: URLFWD
    values:
    - code: 301
      masking: 2
      path: /
      query: 0
      target: https://www.example.com
  - type: MX
    values:
    - exchange: mta.com.
      preference: 1
  - type: TXT
    values:
    - v=spf1 -all
    - v=DKIM1\; p=
_dmarc:
  type: TXT
  value: v=DMARC1\; p=reject\; pct=100\; fo=1\; rua=mailto:person@example.com\;
    ruf=mailto:person@example.com\; ri=3600
www:
  type: URLFWD
  values:
  - code: 301
    masking: 2
    path: /
    query: 0
    target: https://www.example.com
```

**Comment by nakato** [comment] 2022-08-11 01:01
I'm not having any luck reproducing the error with the above zone yaml.

Would you be able to provide a minimal example that reproduces this error including the main config-file?

**Comment by ross** [comment] 2022-08-11 13:02
Sorry, my previous comment was confusing, I was more meaning examples of the `zones` section of the main config. Was trying to get an idea of what sorts of sub-zone setups might run into this problem. I'm going to play around and see if I can come up with something regardless.

**Comment by ross** [comment] 2022-08-11 13:22
Pushed up PR that found unexpected behavior with `Manager.configured_sub_zones`. Haven't yet dug in to what's going on  so early days. Will update that PR with info.

**Comment by brianeclow** [comment] 2022-08-11 16:24
I guess wrong, 😅 

We split our configuration files into domains based on use, to speed synchronization testing and apply times. We also add some additional information to the zone information, which I have removed, to help with tracking "ownership" within our org.

The SplitYAML config:

```yaml
---
manager:
  max_workers: 1
providers:
  data:
    class: octodns.provider.yaml.YamlProvider
    directory: ./data
  nsone:
    api_key: env/NS1
    class: octodns_ns1.Ns1Provider
  route53:
    access_key_id: env/AWS_ACCESS
    class: octodns_route53.Route53Provider
    client_max_attempts: 10
    max_changes: 500
    secret_access_key: env/AWS_SECRET
  split:
    class: octodns.provider.yaml.SplitYamlProvider
    directory: ./data
zones:
  example.com.:
    sources:
    - split
    targets:
    - nsone
    - route53
 ```

The templated zones:

```yaml
---
manager:
  max_workers: 1
providers:
  nsone:
    api_key: env/NS1
    class: octodns_ns1.Ns1Provider
  parked:
    class: octodns.provider.yaml.YamlProvider
    directory: ./parked
    populate_should_replace: true
  parkingEnhancement:
    class: octodns.provider.yaml.YamlProvider
    directory: ./parkingenhancement
    populate_should_replace: true
zones:
  example2.com.:
    sources:
    - parked
    targets:
    - nsone
```

**Comment by ross** [comment] 2022-08-14 18:47
Addressed in https://github.com/octodns/octodns/pull/917

**Closed by ross** 2022-08-14 18:47 UTC
