### ISSUE TITLE
Deletion when syncing from a remote provider to the local Yaml provider.

### ISSUE THREAD

**Issue by quistian** [octodns/octodns#1222] opened 2024-10-16 19:46 UTC
From my testing and operations it seems that when syncing a zone (e.g. clowns.org) from a remote provider (e.g. DigitalOcean) to the local Yaml Provider,  if the local yaml file e.g. clowns.org.yaml contains:

---
bozo:
    type A:
    value: 10.11.12.13

And said record is NO found in the remote DigitalOcean zone:  clowns.org
then when a sync is done from DO ----> localYAML the above record stays unchanged. 

I suppose this is by design? I.e. it's not possible to treat the DO data in some sense as authoritative
and then sync to localYaml and then from there to other remote locales.

Is there a way to perform  a sync from a remote provider that will do a true sync, which may include adds, mods and deletions?

**Comment by ross** [comment] 2024-10-16 20:29
Going to need more details about what you're running. If you only plan (no `--doit`) then the file would be left untouched, but if you apply the changes the local yaml file will be overwritten with the values pulled from DO.

What's you're octoDNS config file look like an what command line and args are you running?

**Comment by quistian** [comment] 2024-10-16 20:50
Ah... That's what I expected --doit to do.  How about in the case (which is what I was testing) where the DO zone has no RRs, .i.e. empty and the local yaml file for that zone say has only one A record. Will the sync with --doit leave the local yaml file empty as well?

**Comment by ross** [comment] 2024-10-16 20:53
`octodns-sync --doit` makes whatever exists in the `sources` exist in the `targets`, if that's nothing then the targets will plan and apply their way to nothing.

**Comment by ross** [comment] 2024-10-16 20:55
Actually there might be an edge case there if the `sources` and empty, the `YamlProvider` target may think there's nothing to do and thus not apply. Hadn't thought about that before since that's not really a common/expected case to have nothing in sources. It should work for everything else except `YamlProvider`. Not sure if that could be cleanly addressed.

**Comment by quistian** [comment] 2024-10-16 20:55
Ok..that's exactly what I though should happen. I will have to dig deeper into the provider I've written for the BlueCat v1 API to see why the yaml RRs are not being overwritten in my test case. Thanks.'

**Comment by quistian** [comment] 2024-10-16 21:27
Here's what I get when my BC zone is empty and there is indeed one local yaml record:


```
$ cat leaf-zones/234.privatelink.openai.azure.com.yaml
---
n234_test:
  ttl: 4800
  type: A
  value: 10.140.94.10

And the sync from an empty BC zone:

....

$ octodns-sync --debug --config config/bcv1_to_yaml.yaml 234.privatelink.openai.azure.com.
....
2024-10-16T17:25:32  [48383631960] INFO  BlueCatProvider[bluecat-v1] populate: found 0 records, exists=True
2024-10-16T17:25:32  [48383631960] DEBUG Manager sync:   planning, zone=234.privatelink.openai.azure.com.
2024-10-16T17:25:32  [48383631960] INFO  YamlProvider[yaml] plan: desired=234.privatelink.openai.azure.com.
2024-10-16T17:25:32  [48383631960] DEBUG Zone __init__: zone=Zone<234.privatelink.openai.azure.com.>, sub_zones=set()
2024-10-16T17:25:32  [48383631960] DEBUG YamlProvider[yaml] populate: name=234.privatelink.openai.azure.com., target=True, lenient=True
2024-10-16T17:25:32  [48383631960] DEBUG Zone __init__: zone=Zone<234.privatelink.openai.azure.com.>, sub_zones=set()
2024-10-16T17:25:32  [48383631960] WARNING YamlProvider[yaml] root NS record supported, but no record is configured for 234.privatelink.openai.azure.com.
2024-10-16T17:25:32  [48383631960] DEBUG Zone changes: zone=Zone<234.privatelink.openai.azure.com.>, target=YamlProvider
2024-10-16T17:25:32  [48383631960] INFO  YamlProvider[yaml] plan:   No changes
2024-10-16T17:25:32  [48383631960] INFO  Plan
********************************************************************************
No changes were planned
********************************************************************************

Here's the config file:


providers:
  bluecat-v1:
    class: octodns_bluecat_v1.BlueCatProvider
    endpoint: env/BAM_ENDPOINT
    username: env/BAM_USER
    password: env/BAM_PW
    confname: env/BAM_CONF
    viewname: env/BAM_VIEW
  yaml:
    class: octodns.provider.yaml.YamlProvider
    directory: ./leaf-zones
    default_ttl: 3600
    enforce_order: True

processors:
  only-a-and-aaaa:
    class: octodns.processor.filter.TypeAllowlistFilter
    allowlist:
      - A
      - AAAA
  no-root-ns:
    class: octodns.processor.filter.IgnoreRootNsFilter

zones:
  '*':
    sources:
      - bluecat-v1
    processors:
      - no-root-ns
      - only-a-and-aaaa
    targets:
      - yaml
```

**Comment by ross** [comment] 2024-10-16 22:47
So yeah, that's the behavior mentioned in https://github.com/octodns/octodns/issues/1222#issuecomment-2417946734, working as expected, if not ideally would.

**Comment by quistian** [comment] 2024-10-17 01:11
What I have found, is if I create an A record, in what was an empty zone, and do the sync (on the above mentioned case), the new A record gets created in the yaml file and the old record does get deleted. So the sync happens... But... octodns-sync says nothing about doing the delete. It says Creates=1, Deletes=0... 

```
$ cat leaf-zones/234.privatelink.openai.azure.com.yaml
---
n234_test:
  ttl: 4800
  type: A
  value: 10.140.94.10
```

$ octodns-sync --doit --config config/bcv1_to_yaml.yaml 234.privatelink.openai.azure.com.
....
2024-10-16T21:03:51  [16374987407960] WARNING YamlProvider[yaml] root NS record supported, but no record is configured for 234.privatelink.openai.azure.com.
2024-10-16T21:03:51  [16374987407960] INFO  YamlProvider[yaml] plan:   Creates=1, Updates=0, Deletes=0, Existing Records=0
2024-10-16T21:03:51  [16374987407960] INFO  Plan
********************************************************************************
* 234.privatelink.openai.azure.com.
********************************************************************************
* yaml (YamlProvider)
*   Create Zone<234.privatelink.openai.azure.com.>
*   Create <ARecord A 3600, z234_do_not_remove.234.privatelink.openai.azure.com., ['10.0.0.1']> (bluecat-v1)
*   Summary: Creates=1, Updates=0, Deletes=0, Existing Records=0
********************************************************************************


2024-10-16T21:03:51  [16374987407960] INFO  YamlProvider[yaml] apply: making 1 changes to 234.privatelink.openai.azure.com.
2024-10-16T21:03:51  [16374987407960] INFO  Manager sync:   1 total changes

$ cat leaf-zones/234.privatelink.openai.azure.com.yaml
---
z234_do_not_remove:
  type: A
  value: 10.0.0.1

```

**Comment by ross** [comment] 2024-10-17 18:26
> What I have found, is if I create an A record, in what was an empty zone, and do the sync (on the above mentioned case), the new A record gets created in the yaml file and the old record does get deleted. So the sync happens... But... octodns-sync says nothing about doing the delete. It says Creates=1, Deletes=0...

Right. That's due to the same reasons as an empty sync doesn't delete anything. This is all expected behavior and I'm not sure if there's a clean way to do otherwise without digging into it and it's not a super high priority as it's behaving correctly and as expected, just the messaging isn't ideal.

https://github.com/octodns/octodns/blob/e30d91783eb0b85507605eb51fcfb75b0773fb26/octodns/provider/yaml.py#L345-L348

**Comment by ross** [comment] 2024-10-17 22:34
Thought of a way to potentially pull off a fully spec/behavior compliant `YamlProvider` today on the :bus: ride home. Results are over in https://github.com/octodns/octodns/pull/1223#pullrequestreview-2376437939. Will have to think about and look over it more closely before it'd move forward. May even hold off for the 2.x timeline.

**Comment by ross** [comment] 2024-11-27 21:12
https://github.com/octodns/octodns/pull/1223 has shipped and I believe that with those changes you should now get the desired behavior. Going to close this now. Feel free to comment/reopen if there's more.

**Closed by ross** 2024-11-27 21:12 UTC
